version: "2.2"

services:

  sun:
    tty: true
    build:
      context: .
      args:
        AUTH_MODE: cert
        PSK: shared-secret
        OUR_IP: 192.168.100.2
        THEIR_IP: 192.168.100.3
        KEY_FILE: key.pem
        CERT_FILE: cert.pem
    networks:
      default_net:
        ipv4_address: 192.168.100.2
    privileged: true

  moon:
    tty: true
    build:
      context: .
      args:
        AUTH_MODE: cert
        PSK: shared-secret
        OUR_IP: 192.168.100.3
        THEIR_IP: 192.168.100.2
        KEY_FILE: key.pem
        CERT_FILE: cert.pem
    networks:
      default_net:
        ipv4_address: 192.168.100.3
    privileged: true

networks:
  default_net:
    ipam:
      config:
        - subnet: 192.168.100.0/24
          ip_range: 192.168.100.0/24
          gateway: 192.168.100.1

